### ISSUE TITLE
Rakenduse ülesseadmine testkeskkonda (5p)

### ISSUE THREAD

**Issue by Viido** [Viido/veebiprojekt#3]
Testkeskkond on keskkond, kus teie ja teie praktikumijuhendaja saavad teie loodud lahendust kasutada testimise ja hindamise eesmärgil. See tähendab, et testkeskkond on ligipääsetav Internetis.

Testkeskkonna eest punktide saamiseks tuleb teil:

1. paigaldada oma projekti lahendus (selle hetkeseis) testkeskonda.
2. tagada, et teie lahendus on testkeskkonnas hindamiseks kättesaadav (igal etapil peaks testkeskkonnas olema kättesaadav hindamiseks esitatud nõuetele vastav lahenduse versioon).
3. lisada projekti Github wikisse viide testkeskkonnale.

**Comment by kkorvel** [comment]
https://teamevotingwebsite.azurewebsites.net/
